# Generated by Django 6.0.4 on 2026-05-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_region_name_region_unique_region_per_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addailyanalytics',
            options={'ordering': ['-date', 'ad'], 'verbose_name_plural': 'Ad Daily Analytics'},
        ),
        migrations.AlterModelOptions(
            name='adregionweight',
            options={'ordering': ['ad', 'region']},
        ),
        migrations.AlterModelOptions(
            name='disability',
            options={'ordering': ['name'], 'verbose_name_plural': 'Disabilities'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='servicesubcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Service Sub-Categories'},
        ),
    ]
