# Generated by Django 5.2.11 on 2026-04-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], max_length=10)),
                ('payment_type', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=10)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('target_age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('target_age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('target_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Soft-delete status. Archived services are hidden.')),
            ],
        ),
    ]
