# Generated by Django 6.0.4 on 2026-05-07 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_region_name_region_unique_region_per_parent'),
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['caregiver', 'is_archived'], name='services_se_caregiv_5aca3b_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['sub_category', 'is_archived'], name='services_se_sub_cat_495d54_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_archived'], name='services_se_categor_ac2d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['region', 'is_archived'], name='services_se_region__7e50b7_idx'),
        ),
    ]
