# Generated by Django 6.0.4 on 2026-05-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-id']},
        ),
    ]
