# Generated by Django 6.0.4 on 2026-05-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False, help_text='Set to True once the user finishes the onboarding flow.'),
        ),
    ]
