# Generated by Django 6.0.4 on 2026-05-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_notification_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='upvote',
            options={'ordering': ['-created_at']},
        ),
    ]
